In [1]:
import numpy as np

In [30]:
import random

In [2]:
a = [i for i in range (10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(b)

numpy.ndarray

In [7]:
b = np.array(b, dtype = float)

In [8]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
b[3]

3.0

In [10]:
b[-1]

9.0

In [11]:
b.ndim


1

In [12]:
b.shape


(10,)

In [14]:
b = np.array([[i for i in range(10)],[i for i in range(10,20)],[i for i in range(20,30)]])

In [15]:
b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [16]:
b.shape


(3, 10)

In [17]:
b.size

30

In [20]:
b.shape

(3, 10)

In [19]:
b.ndim

2

In [21]:
b[2, -1]

29

In [22]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [23]:
c = b[1:, 5:]

In [24]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [26]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 6, 8, 9])

In [27]:
c = a + b


In [28]:
c

array([ 5,  7,  8, 11, 13])

In [33]:
a = np.random.shuffle(a)


TypeError: object of type 'NoneType' has no len()

In [35]:
b = np.random.shuffle(b)

In [36]:
b

In [37]:
print(b)

None


In [38]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [39]:
d = a - b

In [40]:
d


array([ 2, -1,  1,  3,  0])

In [41]:
c = d*2

In [42]:
c


array([ 4, -2,  2,  6,  0])

In [43]:
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [44]:
sp = a@b

In [45]:
sp

104

In [46]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])


In [47]:
A.shape, B.shape

((3, 2), (3, 2))

In [48]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [49]:
D = B - A
D

array([[6, 6],
       [6, 6],
       [6, 6]])

In [50]:
A.shape

(3, 2)

In [51]:
E = ([[1, 2, 3],
     [7, 7, 9]])

In [52]:
E = np.array(E)

In [53]:
E

array([[1, 2, 3],
       [7, 7, 9]])

In [54]:
A.shape[1]

2

In [56]:
E.shape[0]

2

In [57]:
Z = np.dot(A, E)

In [58]:
Z

array([[ 7,  7,  9],
       [23, 25, 33],
       [39, 43, 57]])

In [59]:
E

array([[1, 2, 3],
       [7, 7, 9]])

In [60]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
A.T

array([[0, 2, 4],
       [1, 3, 5]])

In [72]:
F = np.array([[1, 2, 5],
            [-2, 3, 6],
            [3, 4, 7]])

In [64]:
np.linalg.det(F)

-28.00000000000001

In [73]:
np.linalg.matrix_rank(F)

3

In [74]:
np.linalg.inv(F)

array([[ 0.125     , -0.25      ,  0.125     ],
       [-1.33333333,  0.33333333,  0.66666667],
       [ 0.70833333, -0.08333333, -0.29166667]])

In [75]:
a = np.random.randint(0, 20, 10)

In [76]:
a

array([ 4,  5,  4, 10,  8,  4,  3, 15, 14,  4])

In [77]:
a[(a>10) & (a % 2 == 0)]

array([14])

In [80]:
a = np.arange(1, 7).reshape(2,-1)

In [81]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [83]:
no.exp(a)

NameError: name 'no' is not defined

In [84]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [85]:
a.sum()

21

In [86]:
a = np.arange(12).reshape(3,-1)
b = np.arange(12, 24).reshape(-1,4)
a
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [89]:
a + b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [90]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [91]:
a = np.arange(12).reshape(3,-1)

In [92]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a = np.random.randint(0,12,(3,4))


In [94]:
a

array([[ 2,  3, 11, 11],
       [ 3,  8,  3,  0],
       [ 6,  5, 11, 11]])

In [95]:
a.min()


0

In [96]:
a.min(axis = 0)

array([2, 3, 3, 0])

In [97]:
a.mean(axis = 0)

array([3.66666667, 5.33333333, 8.33333333, 7.33333333])

In [98]:
a.std(axis = 0)

array([1.69967317, 2.05480467, 3.77123617, 5.18544973])

In [99]:
import pandas